// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXg2mOydzN21bAmCvoSWrE7rITdXA9Im8',
    appId: '1:763295224404:web:d21d823cba0f0522ee53c1',
    messagingSenderId: '763295224404',
    projectId: 'traveller-d3516',
    authDomain: 'traveller-d3516.firebaseapp.com',
    storageBucket: 'traveller-d3516.appspot.com',
    measurementId: 'G-7MZFC963FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcgKRsMrpanMHR-spKjC-uXR6TnonGiQA',
    appId: '1:763295224404:android:baf93205400c0dc2ee53c1',
    messagingSenderId: '763295224404',
    projectId: 'traveller-d3516',
    storageBucket: 'traveller-d3516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6046dXSJrm4jVpPbFlFMM-n1otGlIKrw',
    appId: '1:763295224404:ios:c84f84c95f9f9251ee53c1',
    messagingSenderId: '763295224404',
    projectId: 'traveller-d3516',
    storageBucket: 'traveller-d3516.appspot.com',
    iosClientId: '763295224404-tcs1mbou3php0ekb2meaql5vuld14vvv.apps.googleusercontent.com',
    iosBundleId: 'com.shristi.traveller',
  );
}
